### ISSUE TITLE
Use standardized relationships

### ISSUE THREAD

**Issue by cthoyt** [ComPath/compath-resources#15]
- Instead of `isPartOf`, use `BFO:0000050` (part of)
- Instead of `equivalentTo`, use `skos:exactMatch`

It doesn't appear in compath-resources, but the inverse relation of  `BFO:0000050` is `BFO:0000051` (has part) which will be useful later

**Comment by sarahbeenie** [comment]
Alright, I will change up the the relationships in the DecoPath ontology to the ones you suggested and upload it to the mappings folder in this repo :)

**Comment by cthoyt** [comment]
Still open until all of the other TSVs are updated

**Comment by ddomingof** [comment]
This is gonna break a lot of things from pathwayforte and compath so it needs be updated there too. If you take care of that I am fine with it

**Comment by cthoyt** [comment]
It's on the list. there are massive refactoring branches for both projects that need a bit more love, but it's getting there
